### ISSUE TITLE
Support Chromium.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ichaoX/ext-textFragment#4]

**Comment by ichaoX** [comment]
Chromium v81+ should support this feature natively.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/4#issuecomment-2214059974

@ichaoX, that's true, although having this available there would mean that I know that I can create identical text directive fragment URIs irrespective of the browser I'm using. Currently, there are minor differences between Firefox and Chromium amonst the few text fragment extensions I've used.

**Comment by ichaoX** [comment]
Indeed, there may be some differences, typically caused by word segmentation and spacing.

Supporting Chromium may not be ideal (due to the need to coexist with native text fragments and ongoing browser differences) and I don't have the time/energy to implement it.

I think a more suitable approach would be to improve the implementation to reduce these differences.
